services:
  server:
    image: ghcr.io/raian621/capstone-server:latest
    ports:
      - "8000:8000"
    environment:
      - APP_ADDRESS=0.0.0.0
      - APP_PORT=8000
      - APP_CLIENT_URL=alpha.transcribro.com
      - APP_LOG_FILE=server.log
      - OPEN_API_KEY=$OPEN_API_KEY
    restart: unless-stopped